---
# tasks file for roles/vdc
- name: create vdc
  no_log: False
  vcd_org_vdc:
    user: "administrator"
    password: "VMware1!"
    host: "10.172.158.109"
    org: "System"
    vdc_name: "{{ vdc_name }}"
    provider_vdc_name: "PVDC1"
    description: "test vdc"
    allocation_model: "AllocationVApp"
    is_enabled: "false"
    storage_profiles: "{ \"name\" : \"Performance\",\"enabled\"  : true, \"units\" : \"MB\", \"limit\" : 0, \"default\" : true }"
    state: "present"
  register: output

- assert:
    that:
      - "'VDC {{ vdc_name }} has been created.' in output.msg"

- name: update vdc
  no_log: False
  vcd_org_vdc:
    user: "administrator"
    password: "VMware1!"
    host: "10.172.158.109"
    org: "System"
    vdc_name: "{{ vdc_name }}"
    is_enabled: "true"
    state: "update"
  register: output

- assert:
    that:
      - "'VDC {{ vdc_name }} has been updated.' in output.msg"

- name: delete vdc
  no_log: False
  vcd_org_vdc:
    user: "administrator"
    password: "VMware1!"
    host: "10.172.158.109"
    org: "System"
    vdc_name: "{{ vdc_name }}"
    state: "absent"
  register: output

- assert:
    that:
      - "'VDC {{ vdc_name }} has been deleted.' in output.msg"