---
# tasks file for roles/vapp
- name: create vapp
  vcd_vapp:
    vapp_name: "{{ vapp_name }}"
    template_name: "centos7"
    catalog_name: "test_catalog"
    vdc: "Terraform_VDC"
    power_on: False
    storage_profile: "Standard"
    state: "present"
  register: output

- name: create vapp output
  debug:
    msg: '{{ output }}'

- name: power on vapp
  vcd_vapp:
    vapp_name: "{{ vapp_name }}"
    template_name: "centos7"
    catalog_name: "test_catalog"
    vdc: "Terraform_VDC"
    operation: "poweron"
  register: output

- name: power on vapp output
  debug:
    msg: '{{ output }}'

- name: power off vapp
  vcd_vapp:
    vapp_name: "{{ vapp_name }}"
    template_name: "centos7"
    catalog_name: "test_catalog"
    vdc: "Terraform_VDC"
    operation: "poweroff"
  register: output

- name: power off vapp output
  debug:
    msg: '{{ output }}'

- name: undeploy vapp
  vcd_vapp:
    vapp_name: "{{ vapp_name }}"
    template_name: "centos7"
    catalog_name: "test_catalog"
    vdc: "Terraform_VDC"
    operation: "undeploy"
  register: output

- name: undeploy vapp output
  debug:
    msg: '{{ output }}'

- name: deploy vapp
  vcd_vapp:
    vapp_name: "{{ vapp_name }}"
    template_name: "centos7"
    catalog_name: "test_catalog"
    vdc: "Terraform_VDC"
    operation: "deploy"
  register: output

- name: deploy vapp output
  debug:
    msg: '{{ output }}'

- name: delete vapp
  vcd_vapp:
    vapp_name: "{{ vapp_name }}"
    template_name: "centos7"
    catalog_name: "test_catalog"
    vdc: "Terraform_VDC"
    state: "absent"
  register: output

- name: delete vapp output
  debug:
    msg: '{{ output }}'